services:
  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: adonis-app
    restart: unless-stopped
    ports:
      - "3333:3333"
    env_file: .env
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - postgres

  postgres:
    image: postgres:16
    container_name: postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER:-default_user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-default_password}
      POSTGRES_DB: ${DB_DATABASE:-default_db}
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
